version: '3.9'
name: fitfriends-160701-backend
services:
  fitfriends-160701.fakesmtp:
    image: gessnerfl/fake-smtp-server:2.2.0
    container_name: 'fitfriends-160701.fakesmtp'
    hostname: 'fitfriends-160701.fakesmtp'
    ports:
      - '${MAIL_SMTP_PORT}:8025'
      - '${MAIL_SMTP_UI_PORT}:8080'
  fitfriends-160701.mongodb:
    image: mongo:4.4
    restart: always
    container_name: fitfriends-160701.mongo

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}

    ports:
      - ${MONGO_PORT}:27017

    volumes:
      - fitfriends-160701:/data/db

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/${MONGO_DB} --quiet
      interval: 10s
      timeout: 10s
      retries: 5
  fitfriends-160701.mongo.ui:
    image: mongo-express
    restart: always
    container_name: fitfriends-160701.mongo.ui

    ports:
      - ${MONGO_UI_PORT}:8081

    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@fitfriends-160701.mongo:27017/

volumes:
  fitfriends-160701:
